version: 2
jobs:
  install:
    docker:
      - image: circleci/node:6.11.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Yarn
          command: sudo npm install -g yarn@~1.0.0

      - run:
          name: Install Project Dependencies
          command: yarn install

      - run:
          name: Run Jest Tests
          command: yarn test --coverage

deploy-stage:
    docker:
      - image: circleci/node:6.11.0

    working_directory: ~/repo
    
    environment: 
      RELEASE_ENV: stage

    steps:
      - run:
          name: Deploy to Staging
          command: [
              echo "Develop branch, releasing to stage"
              yarn run release
              
              
deploy-prod:
    docker:
      - image: circleci/node:6.11.0

    working_directory: ~/repo
    
    environment: 
      RELEASE_ENV: production

    steps:
      - run:
          name: Deploy to Production
          command: [
              echo "Master branch, releasing to production"
              yarn run release
              
build:
    docker:
      - image: circleci/node:6.11.0

    working_directory: ~/repo

    steps:
      - run:
          name: PR Build
          command: [
              echo "CI Build (Non-Master/Non-Develop)"
              yarn run build
              
workflows:
  version: 2
  build-deploy:
    jobs: 
      - install
      - deploy-stage: 
        requires: 
          - install
        filters: 
          branches: 
            only: develop
      - deploy-prod:
        requires: 
          - install
        filters: 
          branches: 
            only: master
      - build:
        requires: install
        filters: 
          branches:
            ignore: 
              - master
              - develop
